### ISSUE TITLE
security: Set up API key

### ISSUE THREAD

**Issue by rKamindo** [COSC381-2024Winter/youtube-api-exercise-rKamindo#1]
**No user story**

**Description**
Generally, config.py should not contain any API key but in the assignment, please still ad config.py to the git repository. Int his way, the grader will be able to run your app

**Tasks**
- [ ] Add a config.py
- [ ] Add a youtube py
- [ ] Test if youtube.py can use the API key

**Acceptance Criteria
1. This API Key can be used anywhere without constraints.

**Acceptance Tests
1. This API key can be imported to another file
2. This API key can be used later for YouTube API
