### ISSUE TITLE
Pagination: get 5 pages using a loop

### ISSUE THREAD

**Issue by rKamindo** [COSC381-2024Winter/youtube-api-exercise-rKamindo#12]
**User Story**
As a user who wants to find the right video, I may not find what I'm looking for in the first page of my search, I want to search at least 5 pages worth.

Persona: a user who wants to find the right video
Feature: show 5 pages of search results
Business Value: user is more likely to find the right video that they were looking for

**Task List**
- [ ] Create a loop that fetches the search result 5 times
- [ ] Print each search result
- [ ] Add handling if there are no more search results

**Acceptance Criteria**
- Runs on Python 3.10 in EC2

**Acceptance Tests**
Given, I run the program
When, I search for cooking videos and set the max results to 1
Then, there are 5 pages of search results printed out
