### ISSUE TITLE
Create ability to search on youtube

### ISSUE THREAD

**Issue by rKamindo** [COSC381-2024Winter/youtube-api-exercise-rKamindo#3]
**User Story**
As a user, I want to be able to search for a video by a key term and see the matching results

**Task List**
- [x] Create a venv
- [x] Activate venv
- [x] Install google-api-python-client
- [x] export venv to a requirements.txt
- [x] build the feature to search in youtube.py
