### ISSUE TITLE
enhancement: Make youtube_search return videos instead of search response

### ISSUE THREAD

**Issue by rKamindo** [COSC381-2024Winter/youtube-api-exercise-rKamindo#4]
As a user who likes to watch online videos, I want to be able to find the videos that I search for, so that I can watch them quickly

**Persona: a user who likes to watch online video
**Feature**: provide a video list to the user
**Business Value**:

**Tasks**
- [ ] iterate through the response and find the videos
- [ ] exclude the channels/playlists from the results
- [ ] make sure we return up to the max number of results
- [ ] return the list of videos
- [ ] in the main entry point, print the videos

**Acceptance Criteria**
1. It can run in Python 3.10

**Acceptance**
1. Search "Harry Potter" with maxResults = 3 and it should return exactly three videos about Harry Potter
2. Search "asdjsakdjsa;dasgfddggd;gdsagdgdag;fsdadfsadfsa" with maxResults = 1 nd it should return "no results"
3.
