### ISSUE TITLE
Pagination: get a second page

### ISSUE THREAD

**Issue by rKamindo** [COSC381-2024Winter/youtube-api-exercise-rKamindo#8]
**User Story**
As a user, I want to be able to request the next page of search results, this is because there may be too many results to show at once

**Tasks**
- [x] Get the next page token
- [x] Use the next page token to get the next page
- [x] Print the second page
